from sqlalchemy.orm import Session
from ..services import operations_service

def list_trainers(db: Session, **params): return operations_service.list_trainers(db, **params)
def create_trainer(db: Session, payload: dict, actor=None): return operations_service.create_trainer(db, payload, actor)
def update_trainer(db: Session, trainer_id: int, payload: dict, actor=None): return operations_service.update_trainer(db, trainer_id, payload, actor)
def delete_trainer(db: Session, trainer_id: int, actor=None): return operations_service.delete_trainer(db, trainer_id, actor)
def list_pt(db: Session, **params): return operations_service.list_pt(db, **params)
def create_pt(db: Session, member_id: int, payload: dict, actor=None): return operations_service.create_pt(db, member_id, payload, actor)
def update_pt(db: Session, enrollment_id: int, payload: dict, actor=None): return operations_service.update_pt(db, enrollment_id, payload, actor)
def checkin_candidates(db: Session, q: str): return operations_service.checkin_candidates(db, q)
def recent_checkins(db: Session, limit: int): return operations_service.recent_checkins(db, limit)
def create_checkin(db: Session, payload: dict, actor=None): return operations_service.create_checkin(db, payload, actor)
def checkout(db: Session, session_id: int, actor=None): return operations_service.checkout(db, session_id, actor)
def list_payments(db: Session, **params): return operations_service.list_payments(db, **params)
def settings(db: Session): return operations_service.settings(db)
def create_job_title(db: Session, payload: dict, actor=None): return operations_service.create_job_title(db, payload, actor)
def update_job_title(db: Session, title_id: int, payload: dict, actor=None): return operations_service.update_job_title(db, title_id, payload, actor)
def delete_job_title(db: Session, title_id: int, actor=None): return operations_service.delete_job_title(db, title_id, actor)
def create_bank_account(db: Session, payload: dict, actor=None): return operations_service.create_bank_account(db, payload, actor)
def update_bank_account(db: Session, account_id: int, payload: dict, actor=None): return operations_service.update_bank_account(db, account_id, payload, actor)
def delete_bank_account(db: Session, account_id: int, actor=None): return operations_service.delete_bank_account(db, account_id, actor)
