from sqlalchemy.orm import Session
from ..services import operations_service

def list_trainers(db: Session, **params): return operations_service.list_trainers(db, **params)
def employee_attendance(db: Session, day: str): return operations_service.employee_attendance(db, day)
def employee_shift_report(db: Session, **params): return operations_service.employee_shift_report(db, **params)
def approve_employee_shift_override(db: Session, shift_id: int, payload: dict, actor=None): return operations_service.approve_employee_shift_override(db, shift_id, payload, actor)
def update_employee_shift_attendance_events(db: Session, shift_id: int, payload: dict, actor=None): return operations_service.update_employee_shift_attendance_events(db, shift_id, payload, actor)
def create_trainer(db: Session, payload: dict, actor=None): return operations_service.create_trainer(db, payload, actor)
def update_trainer(db: Session, trainer_id: int, payload: dict, actor=None): return operations_service.update_trainer(db, trainer_id, payload, actor)
def delete_trainer(db: Session, trainer_id: int, actor=None): return operations_service.delete_trainer(db, trainer_id, actor)
def list_employee_shifts(db: Session, employee_id: int, **params): return operations_service.list_employee_shifts(db, employee_id, **params)
def list_employee_shifts_week(db: Session, **params): return operations_service.list_employee_shifts_week(db, **params)
def create_employee_shift(db: Session, employee_id: int, payload: dict, actor=None): return operations_service.create_employee_shift(db, employee_id, payload, actor)
def create_employee_shifts_bulk(db: Session, employee_id: int, payload: dict, actor=None): return operations_service.create_employee_shifts_bulk(db, employee_id, payload, actor)
def import_employee_shifts(db: Session, payload: dict, actor=None): return operations_service.import_employee_shifts(db, payload, actor)
def preview_employee_shift_excel(file_bytes: bytes, filename: str = ""): return operations_service.preview_employee_shift_excel(file_bytes, filename)
def replace_employee_shifts_week(db: Session, payload: dict, actor=None): return operations_service.replace_employee_shifts_week(db, payload, actor)
def update_employee_shift(db: Session, shift_id: int, payload: dict, actor=None): return operations_service.update_employee_shift(db, shift_id, payload, actor)
def delete_employee_shift(db: Session, shift_id: int, actor=None): return operations_service.delete_employee_shift(db, shift_id, actor)
def list_pt(db: Session, **params): return operations_service.list_pt(db, **params)
def create_pt(db: Session, member_id: int, payload: dict, actor=None): return operations_service.create_pt(db, member_id, payload, actor)
def update_pt(db: Session, enrollment_id: int, payload: dict, actor=None): return operations_service.update_pt(db, enrollment_id, payload, actor)
def adjust_pt_sessions(db: Session, enrollment_id: int, payload: dict, actor=None): return operations_service.adjust_pt_sessions(db, enrollment_id, payload, actor)
def checkin_candidates(db: Session, q: str): return operations_service.checkin_candidates(db, q)
def recent_checkins(db: Session, **params): return operations_service.recent_checkins(db, **params)
def create_checkin(db: Session, payload: dict, actor=None): return operations_service.create_checkin(db, payload, actor)
def checkout(db: Session, session_id: int, actor=None): return operations_service.checkout(db, session_id, actor)
def member_processing_queue(db: Session, **params): return operations_service.member_processing_queue(db, **params)
def process_member_checkin(db: Session, session_id: int, payload: dict, actor=None): return operations_service.process_member_checkin(db, session_id, payload, actor)
def list_payments(db: Session, **params): return operations_service.list_payments(db, **params)
def settings(db: Session): return operations_service.settings(db)
def create_job_title(db: Session, payload: dict, actor=None): return operations_service.create_job_title(db, payload, actor)
def update_job_title(db: Session, title_id: int, payload: dict, actor=None): return operations_service.update_job_title(db, title_id, payload, actor)
def delete_job_title(db: Session, title_id: int, actor=None): return operations_service.delete_job_title(db, title_id, actor)
def create_bank_account(db: Session, payload: dict, actor=None): return operations_service.create_bank_account(db, payload, actor)
def update_bank_account(db: Session, account_id: int, payload: dict, actor=None): return operations_service.update_bank_account(db, account_id, payload, actor)
def delete_bank_account(db: Session, account_id: int, actor=None): return operations_service.delete_bank_account(db, account_id, actor)
