import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { api, queryString } from '../../services/api'
import { PageHeader } from '../../components/common/PageHeader'
import { DataTable } from '../../components/ui/DataTable'
import { Input } from '../../components/ui/Form'
import { money, shortDate } from '../../utils/format'

const methodLabels={cash:'Tiền mặt',bank_transfer:'Chuyển khoản',card:'Thẻ',apple_pay:'Apple Pay'}
export function ReportsPage(){const[dateFrom,setDateFrom]=useState('');const[dateTo,setDateTo]=useState('');const query=useQuery({queryKey:['reports',dateFrom,dateTo],queryFn:()=>api(`/api/reports?${queryString({dateFrom,dateTo})}`)});const data=query.data;return <><PageHeader eyebrow="Phân tích" title="Báo cáo" description="Doanh thu, check-in và công nợ hỗ trợ quyết định vận hành."/><div className="toolbar"><span className="text-xs font-medium text-slate-600">Khoảng thời gian</span><Input className="input w-40" type="date" value={dateFrom} onChange={(e)=>setDateFrom(e.target.value)}/><span className="text-slate-300">→</span><Input className="input w-40" type="date" value={dateTo} onChange={(e)=>setDateTo(e.target.value)}/></div><div className="metric-strip grid-cols-4">{[['Doanh thu',money(data?.summary.revenue)],['Số phiếu thu',data?.summary.payments||0],['Hội viên hoạt động',data?.summary.activeMembers||0],['Lượt check-in',data?.summary.checkins||0]].map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="section-grid"><section><div className="section-header"><div><h2>Doanh thu theo phương thức</h2><p>Cơ cấu thu tiền trong kỳ</p></div></div><div className="definition-list border-y border-slate-200 bg-white px-4">{data?.revenueByMethod.map((row)=><div key={row.method}><dt>{methodLabels[row.method]||row.method}</dt><dd className="text-right font-medium">{money(row.amount)}</dd></div>)}</div></section><section><div className="section-header"><div><h2>Tổng công nợ</h2><p>Các khoản cần thu</p></div></div><div className="panel"><strong className="text-xl font-semibold text-slate-900">{money(data?.debts.reduce((sum,row)=>sum+row.amount,0))}</strong><p className="mt-1 text-xs text-slate-500">{data?.debts.length||0} gói còn dư nợ</p></div></section></div><section className="mt-7"><div className="section-header"><div><h2>Chi tiết công nợ</h2><p>Ưu tiên các khoản đã quá hạn</p></div></div><DataTable loading={query.isLoading} rows={data?.debts} columns={[{key:'member',label:'Hội viên',render:(r)=><span className="cell-primary">{r.member}</span>},{key:'package',label:'Gói tập'},{key:'amount',label:'Số tiền',className:'text-right',render:(r)=>money(r.amount)},{key:'dueDate',label:'Hạn thanh toán',render:(r)=>shortDate(r.dueDate)},{key:'status',label:'Tình trạng',render:(r)=><span className={r.overdue?'text-xs font-medium text-red-700':'text-xs text-slate-500'}>{r.overdue?'Quá hạn':'Trong hạn'}</span>}]} emptyTitle="Không có công nợ" emptyDescription="Tất cả gói tập đã được thanh toán đầy đủ."/></section></>}
