import { useEffect, useState } from 'react'
import { format } from 'date-fns'
import { Button } from '../ui/Button'
import { Field, Input, Select } from '../ui/Form'
import { Modal } from '../ui/Modal'
import { SearchableSelect } from '../ui/SearchableSelect'

const weekdays = ['Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6','Thứ 7','Chủ nhật']
export function TrainingForm({ enrollment, options, open, onClose, onSubmit, pending, error }) {
  const [form,setForm]=useState({})
  useEffect(()=>setForm(enrollment?{coachId:enrollment.coach?.id||'',type:enrollment.type,totalSessions:enrollment.totalSessions,remainingSessions:enrollment.remainingSessions,startsAt:enrollment.startsAt||'',expiresAt:enrollment.expiresAt||'',scheduleDays:enrollment.scheduleDays||[],scheduleTime:enrollment.scheduleTime||'',status:enrollment.status}:{coachId:'',type:'1:1',totalSessions:12,startsAt:format(new Date(),'yyyy-MM-dd'),expiresAt:'',scheduleDays:[],scheduleTime:'',status:'active'}),[enrollment,open])
  const toggle=(day)=>setForm({...form,scheduleDays:form.scheduleDays.includes(day)?form.scheduleDays.filter((value)=>value!==day):[...form.scheduleDays,day]})
  const coaches=options?.employees?.filter((row)=>/coach|pt/i.test(row.title||''))||[]
  const sessionPreset=[12,24,36].includes(Number(form.totalSessions))?String(form.totalSessions):'other'
  return <Modal open={open} onClose={onClose} title={enrollment?'Chỉnh sửa PT':'Đăng ký PT'} description="Thiết lập hình thức, coach và lịch tập." size="lg"><form onSubmit={(event)=>{event.preventDefault();onSubmit(form)}}><div className="modal-body"><div className="form-grid"><Field label="Hình thức"><Select value={form.type||'1:1'} onChange={(e)=>setForm({...form,type:e.target.value})}><option>1:1</option><option>1:2</option><option>1:3</option></Select></Field><Field label="Coach" required><SearchableSelect value={form.coachId||''} onChange={(coachId)=>setForm({...form,coachId})} placeholder="Chọn coach" searchPlaceholder="Tên hoặc mã nhân viên…" options={coaches.map((row)=>({value:row.id,label:row.name,meta:row.title}))}/></Field><Field label="Tổng số buổi"><Select value={sessionPreset} onChange={(e)=>setForm({...form,totalSessions:e.target.value==='other'?1:Number(e.target.value)})}><option value="12">12 buổi</option><option value="24">24 buổi</option><option value="36">36 buổi</option><option value="other">Khác</option></Select></Field>{sessionPreset==='other'&&<Field label="Số buổi khác"><Input type="number" min="1" value={form.totalSessions||1} onChange={(e)=>setForm({...form,totalSessions:Number(e.target.value)})}/></Field>}{enrollment&&<Field label="Số buổi còn lại"><Input type="number" min="0" value={form.remainingSessions??0} onChange={(e)=>setForm({...form,remainingSessions:Number(e.target.value)})}/></Field>}<Field label="Ngày bắt đầu"><Input type="date" value={form.startsAt||''} onChange={(e)=>setForm({...form,startsAt:e.target.value})}/></Field><Field label="Ngày hết hạn"><Input type="date" value={form.expiresAt||''} onChange={(e)=>setForm({...form,expiresAt:e.target.value})}/></Field><Field className="form-span" label="Ngày tập"><div className="flex flex-wrap gap-2">{weekdays.map((day)=><button key={day} type="button" onClick={()=>toggle(day)} className={`rounded-md border px-2.5 py-1.5 text-xs ${form.scheduleDays?.includes(day)?'border-navy-800 bg-navy-900 text-white':'border-slate-200 bg-white text-slate-600'}`}>{day}</button>)}</div></Field><Field label="Giờ tập"><Input type="time" value={form.scheduleTime||''} onChange={(e)=>setForm({...form,scheduleTime:e.target.value})}/></Field>{enrollment&&<Field label="Trạng thái"><Select value={form.status||'active'} onChange={(e)=>setForm({...form,status:e.target.value})}><option value="active">Đang tập</option><option value="completed">Hoàn thành</option><option value="inactive">Ngừng</option></Select></Field>}</div>{error&&<div className="inline-error mt-4">{error}</div>}</div><div className="form-actions"><Button variant="secondary" onClick={onClose}>Hủy</Button><Button type="submit" disabled={pending}>{pending?'Đang lưu…':'Lưu đăng ký PT'}</Button></div></form></Modal>
}
