import { useQuery } from '@tanstack/react-query'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Link } from 'react-router-dom'
import { api } from '../../services/api'
import { PageHeader } from '../../components/common/PageHeader'
import { DataTable } from '../../components/ui/DataTable'
import { StatusBadge } from '../../components/ui/StatusBadge'
import { dateTime, money } from '../../utils/format'

export function DashboardPage() {
  const query = useQuery({ queryKey: ['dashboard'], queryFn: () => api('/api/dashboard') }); const data = query.data
  const metrics = data ? [{label:'Tổng hội viên',value:data.metrics.totalMembers,to:'/members'},{label:'Đang hoạt động',value:data.metrics.activeMembers,to:'/members?view=active'},{label:'Check-in hôm nay',value:data.metrics.checkinsToday,to:'/check-in'},{label:'Sắp hết hạn',value:data.metrics.expiringSoon,to:'/members?view=expiring'},{label:'Doanh thu tháng',value:money(data.metrics.revenueMonth),to:'/payments'},{label:'Công nợ',value:money(data.metrics.outstanding),to:'/members?view=debt'}] : []
  return <><PageHeader eyebrow="Tổng quan vận hành" title="Dashboard" description="Những tín hiệu cần theo dõi trong ngày hôm nay." />
    <div className="metric-strip">{query.isLoading ? Array.from({ length: 6 }).map((_, i) => <div className="metric" key={i}><div className="skeleton mb-2 h-3 w-20" /><div className="skeleton h-6 w-24" /></div>) : metrics.map((metric) => <Link className="metric hover:bg-slate-50" key={metric.label} to={metric.to}><span>{metric.label}</span><strong>{metric.value}</strong></Link>)}</div>
    <div className="section-grid"><section className="section"><div className="section-header"><div><h2>Hoạt động check-in</h2><p>7 ngày gần nhất</p></div></div><div className="panel h-[250px]">{data && <ResponsiveContainer width="100%" height="100%"><AreaChart data={data.activity} margin={{ top: 12, right: 10, left: -25, bottom: 0 }}><defs><linearGradient id="activity" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#163A5F" stopOpacity={0.16}/><stop offset="95%" stopColor="#163A5F" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#94a3b8' }} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#94a3b8' }} /><Tooltip contentStyle={{ border: '1px solid #e2e8f0', borderRadius: 6, boxShadow: '0 8px 20px rgba(15,23,42,.08)', fontSize: 12 }} /><Area type="monotone" dataKey="checkins" stroke="#163A5F" strokeWidth={2} fill="url(#activity)" /></AreaChart></ResponsiveContainer>}</div></section>
      <section className="section"><div className="section-header"><div><h2>Trạng thái gói tập</h2><p>Phân bổ hiện tại</p></div></div><div className="panel"><div className="definition-list">{Object.entries(data?.membershipStatus || {}).map(([status, count]) => <div key={status}><dt><StatusBadge status={status} /></dt><dd className="text-right font-semibold">{count}</dd></div>)}</div></div></section></div>
    <div className="section-grid"><section className="section"><div className="section-header"><div><h2>Hội viên cần xử lý</h2><p>Hết hạn hoặc còn công nợ</p></div><Link to="/members">Xem hội viên</Link></div><DataTable loading={query.isLoading} rows={data?.attention} columns={[{ key: 'member', label: 'Hội viên', render: (row) => <Link className="cell-primary hover:underline" to={`/members/${row.memberId}`}>{row.member}<div className="cell-secondary">{row.code}</div></Link> }, { key: 'issue', label: 'Vấn đề' }, { key: 'action', label: '', className: 'text-right', render: (row) => <Link className="text-xs font-medium text-navy-700 hover:underline" to={`/members/${row.memberId}`}>Xử lý</Link> }]} emptyTitle="Không có vấn đề cần xử lý" emptyDescription="Mọi gói tập và công nợ hiện đang ổn định." /></section>
      <section className="section"><div className="section-header"><div><h2>Check-in gần đây</h2><p>Hoạt động mới nhất</p></div><Link to="/check-in">Mở quầy check-in</Link></div><DataTable loading={query.isLoading} rows={data?.recentCheckins} columns={[{ key: 'member', label: 'Hội viên', render: (row) => <div><span className="cell-primary">{row.member}</span><div className="cell-secondary">{row.code}</div></div> }, { key: 'time', label: 'Thời gian', render: (row) => dateTime(row.time) }, { key: 'status', label: 'Trạng thái', render: (row) => <StatusBadge status={row.status} /> }]} /></section></div>
  </>
}
